/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An API for MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * MLB Division 
 * @export
 * @interface Division
 */
export interface Division {
    /**
     * 
     * @type {number}
     * @memberof Division
     */
    id?: number;
}

/**
 * Check if a given object implements the Division interface.
 */
export function instanceOfDivision(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DivisionFromJSON(json: any): Division {
    return DivisionFromJSONTyped(json, false);
}

export function DivisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Division {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function DivisionToJSON(value?: Division | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

