/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An API for MLB Stat API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GameContent
 */
export interface GameContent {
  /**
   *
   * @type {string}
   * @memberof GameContent
   */
  link?: string;
}

/**
 * Check if a given object implements the GameContent interface.
 */
export function instanceOfGameContent(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GameContentFromJSON(json: any): GameContent {
  return GameContentFromJSONTyped(json, false);
}

export function GameContentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GameContent {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    link: !exists(json, "link") ? undefined : json["link"],
  };
}

export function GameContentToJSON(value?: GameContent | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    link: value.link,
  };
}
