/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An API for MLB Stat API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GameTeam } from "./GameTeam";
import {
  GameTeamFromJSON,
  GameTeamFromJSONTyped,
  GameTeamToJSON,
} from "./GameTeam";

/**
 *
 * @export
 * @interface GameTeams
 */
export interface GameTeams {
  /**
   *
   * @type {GameTeam}
   * @memberof GameTeams
   */
  away?: GameTeam;
  /**
   *
   * @type {GameTeam}
   * @memberof GameTeams
   */
  home?: GameTeam;
}

/**
 * Check if a given object implements the GameTeams interface.
 */
export function instanceOfGameTeams(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GameTeamsFromJSON(json: any): GameTeams {
  return GameTeamsFromJSONTyped(json, false);
}

export function GameTeamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GameTeams {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    away: !exists(json, "away") ? undefined : GameTeamFromJSON(json["away"]),
    home: !exists(json, "home") ? undefined : GameTeamFromJSON(json["home"]),
  };
}

export function GameTeamsToJSON(value?: GameTeams | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    away: GameTeamToJSON(value.away),
    home: GameTeamToJSON(value.home),
  };
}
