/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An API for MLB Stat API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Game } from "./Game";
import { GameFromJSON, GameFromJSONTyped, GameToJSON } from "./Game";

/**
 * MLB Date
 * @export
 * @interface GameDate
 */
export interface GameDate {
  /**
   *
   * @type {string}
   * @memberof GameDate
   */
  date?: string;
  /**
   *
   * @type {number}
   * @memberof GameDate
   */
  totalItems?: number;
  /**
   *
   * @type {number}
   * @memberof GameDate
   */
  totalEvents?: number;
  /**
   *
   * @type {number}
   * @memberof GameDate
   */
  totalGames?: number;
  /**
   *
   * @type {number}
   * @memberof GameDate
   */
  totalGamesInProgress?: number;
  /**
   *
   * @type {Array<Game>}
   * @memberof GameDate
   */
  games?: Array<Game>;
}

/**
 * Check if a given object implements the GameDate interface.
 */
export function instanceOfGameDate(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GameDateFromJSON(json: any): GameDate {
  return GameDateFromJSONTyped(json, false);
}

export function GameDateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GameDate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    date: !exists(json, "date") ? undefined : json["date"],
    totalItems: !exists(json, "totalItems") ? undefined : json["totalItems"],
    totalEvents: !exists(json, "totalEvents") ? undefined : json["totalEvents"],
    totalGames: !exists(json, "totalGames") ? undefined : json["totalGames"],
    totalGamesInProgress: !exists(json, "totalGamesInProgress")
      ? undefined
      : json["totalGamesInProgress"],
    games: !exists(json, "games")
      ? undefined
      : (json["games"] as Array<any>).map(GameFromJSON),
  };
}

export function GameDateToJSON(value?: GameDate | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    date: value.date,
    totalItems: value.totalItems,
    totalEvents: value.totalEvents,
    totalGames: value.totalGames,
    totalGamesInProgress: value.totalGamesInProgress,
    games:
      value.games === undefined
        ? undefined
        : (value.games as Array<any>).map(GameToJSON),
  };
}
