/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An API for MLB Stat API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GameTeamLeagueRecord
 */
export interface GameTeamLeagueRecord {
  /**
   *
   * @type {number}
   * @memberof GameTeamLeagueRecord
   */
  wins?: number;
  /**
   *
   * @type {number}
   * @memberof GameTeamLeagueRecord
   */
  losses?: number;
  /**
   *
   * @type {string}
   * @memberof GameTeamLeagueRecord
   */
  pct?: string;
}

/**
 * Check if a given object implements the GameTeamLeagueRecord interface.
 */
export function instanceOfGameTeamLeagueRecord(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GameTeamLeagueRecordFromJSON(json: any): GameTeamLeagueRecord {
  return GameTeamLeagueRecordFromJSONTyped(json, false);
}

export function GameTeamLeagueRecordFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GameTeamLeagueRecord {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    wins: !exists(json, "wins") ? undefined : json["wins"],
    losses: !exists(json, "losses") ? undefined : json["losses"],
    pct: !exists(json, "pct") ? undefined : json["pct"],
  };
}

export function GameTeamLeagueRecordToJSON(
  value?: GameTeamLeagueRecord | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    wins: value.wins,
    losses: value.losses,
    pct: value.pct,
  };
}
