/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An API for MLB Stat API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * MLB League
 * @export
 * @interface League
 */
export interface League {
  /**
   *
   * @type {number}
   * @memberof League
   */
  id?: number;
}

/**
 * Check if a given object implements the League interface.
 */
export function instanceOfLeague(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function LeagueFromJSON(json: any): League {
  return LeagueFromJSONTyped(json, false);
}

export function LeagueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): League {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
  };
}

export function LeagueToJSON(value?: League | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
  };
}
