/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An API for MLB Stat API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Season } from "./Season";
import { SeasonFromJSON, SeasonFromJSONTyped, SeasonToJSON } from "./Season";

/**
 * MLB Seasons
 * @export
 * @interface Seasons
 */
export interface Seasons {
  /**
   *
   * @type {Array<Season>}
   * @memberof Seasons
   */
  seasons?: Array<Season>;
}

/**
 * Check if a given object implements the Seasons interface.
 */
export function instanceOfSeasons(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SeasonsFromJSON(json: any): Seasons {
  return SeasonsFromJSONTyped(json, false);
}

export function SeasonsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Seasons {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    seasons: !exists(json, "seasons")
      ? undefined
      : (json["seasons"] as Array<any>).map(SeasonFromJSON),
  };
}

export function SeasonsToJSON(value?: Seasons | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    seasons:
      value.seasons === undefined
        ? undefined
        : (value.seasons as Array<any>).map(SeasonToJSON),
  };
}
