/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An API for MLB Stat API 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * MLB Sport
 * @export
 * @interface Sport
 */
export interface Sport {
    /**
     * 
     * @type {number}
     * @memberof Sport
     */
    id?: number;
}

/**
 * Check if a given object implements the Sport interface.
 */
export function instanceOfSport(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SportFromJSON(json: any): Sport {
    return SportFromJSONTyped(json, false);
}

export function SportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function SportToJSON(value?: Sport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

