/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An API for MLB Stat API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Team } from "./Team";
import { TeamFromJSON, TeamFromJSONTyped, TeamToJSON } from "./Team";

/**
 * MLB Teams
 * @export
 * @interface Teams
 */
export interface Teams {
  /**
   *
   * @type {Array<Team>}
   * @memberof Teams
   */
  teams?: Array<Team>;
}

/**
 * Check if a given object implements the Teams interface.
 */
export function instanceOfTeams(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function TeamsFromJSON(json: any): Teams {
  return TeamsFromJSONTyped(json, false);
}

export function TeamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Teams {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    teams: !exists(json, "teams")
      ? undefined
      : (json["teams"] as Array<any>).map(TeamFromJSON),
  };
}

export function TeamsToJSON(value?: Teams | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    teams:
      value.teams === undefined
        ? undefined
        : (value.teams as Array<any>).map(TeamToJSON),
  };
}
