/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An API for MLB Stat API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * MLB Venue
 * @export
 * @interface Venue
 */
export interface Venue {
  /**
   *
   * @type {number}
   * @memberof Venue
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Venue
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Venue
   */
  link?: string;
}

/**
 * Check if a given object implements the Venue interface.
 */
export function instanceOfVenue(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function VenueFromJSON(json: any): Venue {
  return VenueFromJSONTyped(json, false);
}

export function VenueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Venue {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    name: !exists(json, "name") ? undefined : json["name"],
    link: !exists(json, "link") ? undefined : json["link"],
  };
}

export function VenueToJSON(value?: Venue | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    link: value.link,
  };
}
