/* tslint:disable */
/* eslint-disable */
/**
 * MLB StatAPI
 * An spec API to consume the MLB Stat API
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MLBTeamRecord1
 */
export interface MLBTeamRecord1 {
  /**
   *
   * @type {number}
   * @memberof MLBTeamRecord1
   */
  wins?: number;
  /**
   *
   * @type {number}
   * @memberof MLBTeamRecord1
   */
  losses?: number;
  /**
   *
   * @type {number}
   * @memberof MLBTeamRecord1
   */
  ties?: number;
  /**
   *
   * @type {string}
   * @memberof MLBTeamRecord1
   */
  pct?: string;
}

/**
 * Check if a given object implements the MLBTeamRecord1 interface.
 */
export function instanceOfMLBTeamRecord1(
  value: object,
): value is MLBTeamRecord1 {
  return true;
}

export function MLBTeamRecord1FromJSON(json: any): MLBTeamRecord1 {
  return MLBTeamRecord1FromJSONTyped(json, false);
}

export function MLBTeamRecord1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MLBTeamRecord1 {
  if (json == null) {
    return json;
  }
  return {
    wins: json["wins"] == null ? undefined : json["wins"],
    losses: json["losses"] == null ? undefined : json["losses"],
    ties: json["ties"] == null ? undefined : json["ties"],
    pct: json["pct"] == null ? undefined : json["pct"],
  };
}

export function MLBTeamRecord1ToJSON(value?: MLBTeamRecord1 | null): any {
  if (value == null) {
    return value;
  }
  return {
    wins: value["wins"],
    losses: value["losses"],
    ties: value["ties"],
    pct: value["pct"],
  };
}
