AWSTemplateFormatVersion: 2010-09-09
Description: >-
  lambda

Transform:
- AWS::Serverless-2016-10-31

Resources:
  getSeasonStandings:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getSeasonStandings.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SeasonStandingsTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          SEASON_STANDINGS_TABLE: !Ref SeasonStandingsTable
          DEVENV: OSX
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{season}/{league}
            Method: GET
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - src/handlers/getSeasonStandings.ts

  SeasonStandingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SeasonStandingsTable
      AttributeDefinitions:
        - AttributeName: season
          AttributeType: S
        - AttributeName: league
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: season
          KeyType: HASH
        - AttributeName: league
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
