/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char123seasonIdChar125IndexRouteImport } from './routes/{$seasonId}/index'
import { Route as Char123seasonIdChar125Char123teamIdChar125RouteImport } from './routes/{$seasonId}/{$teamId}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123seasonIdChar125IndexRoute =
  Char123seasonIdChar125IndexRouteImport.update({
    id: '/{$seasonId}/',
    path: '/{$seasonId}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123seasonIdChar125Char123teamIdChar125Route =
  Char123seasonIdChar125Char123teamIdChar125RouteImport.update({
    id: '/{$seasonId}/{$teamId}',
    path: '/{$seasonId}/{$teamId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/{$seasonId}/{$teamId}': typeof Char123seasonIdChar125Char123teamIdChar125Route
  '/{$seasonId}/': typeof Char123seasonIdChar125IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/{$seasonId}/{$teamId}': typeof Char123seasonIdChar125Char123teamIdChar125Route
  '/{$seasonId}': typeof Char123seasonIdChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/{$seasonId}/{$teamId}': typeof Char123seasonIdChar125Char123teamIdChar125Route
  '/{$seasonId}/': typeof Char123seasonIdChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/{$seasonId}/{$teamId}' | '/{$seasonId}/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/{$seasonId}/{$teamId}' | '/{$seasonId}'
  id: '__root__' | '/' | '/{$seasonId}/{$teamId}' | '/{$seasonId}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char123seasonIdChar125Char123teamIdChar125Route: typeof Char123seasonIdChar125Char123teamIdChar125Route
  Char123seasonIdChar125IndexRoute: typeof Char123seasonIdChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{$seasonId}/': {
      id: '/{$seasonId}/'
      path: '/{$seasonId}'
      fullPath: '/{$seasonId}/'
      preLoaderRoute: typeof Char123seasonIdChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{$seasonId}/{$teamId}': {
      id: '/{$seasonId}/{$teamId}'
      path: '/{$seasonId}/{$teamId}'
      fullPath: '/{$seasonId}/{$teamId}'
      preLoaderRoute: typeof Char123seasonIdChar125Char123teamIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char123seasonIdChar125Char123teamIdChar125Route:
    Char123seasonIdChar125Char123teamIdChar125Route,
  Char123seasonIdChar125IndexRoute: Char123seasonIdChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
