/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char123sportIdChar125IndexRouteImport } from './routes/{$sportId}/index'
import { Route as Char123sportIdChar125Char123seasonIdChar125IndexRouteImport } from './routes/{$sportId}/{$seasonId}/index'
import { Route as Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRouteImport } from './routes/{$sportId}/{$seasonId}/{$teamId}/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123sportIdChar125IndexRoute =
  Char123sportIdChar125IndexRouteImport.update({
    id: '/{$sportId}/',
    path: '/{$sportId}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123sportIdChar125Char123seasonIdChar125IndexRoute =
  Char123sportIdChar125Char123seasonIdChar125IndexRouteImport.update({
    id: '/{$sportId}/{$seasonId}/',
    path: '/{$sportId}/{$seasonId}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRoute =
  Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRouteImport.update(
    {
      id: '/{$sportId}/{$seasonId}/{$teamId}/',
      path: '/{$sportId}/{$seasonId}/{$teamId}/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/{$sportId}/': typeof Char123sportIdChar125IndexRoute
  '/{$sportId}/{$seasonId}/': typeof Char123sportIdChar125Char123seasonIdChar125IndexRoute
  '/{$sportId}/{$seasonId}/{$teamId}/': typeof Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/{$sportId}': typeof Char123sportIdChar125IndexRoute
  '/{$sportId}/{$seasonId}': typeof Char123sportIdChar125Char123seasonIdChar125IndexRoute
  '/{$sportId}/{$seasonId}/{$teamId}': typeof Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/{$sportId}/': typeof Char123sportIdChar125IndexRoute
  '/{$sportId}/{$seasonId}/': typeof Char123sportIdChar125Char123seasonIdChar125IndexRoute
  '/{$sportId}/{$seasonId}/{$teamId}/': typeof Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/{$sportId}/'
    | '/{$sportId}/{$seasonId}/'
    | '/{$sportId}/{$seasonId}/{$teamId}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/{$sportId}'
    | '/{$sportId}/{$seasonId}'
    | '/{$sportId}/{$seasonId}/{$teamId}'
  id:
    | '__root__'
    | '/'
    | '/{$sportId}/'
    | '/{$sportId}/{$seasonId}/'
    | '/{$sportId}/{$seasonId}/{$teamId}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char123sportIdChar125IndexRoute: typeof Char123sportIdChar125IndexRoute
  Char123sportIdChar125Char123seasonIdChar125IndexRoute: typeof Char123sportIdChar125Char123seasonIdChar125IndexRoute
  Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRoute: typeof Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{$sportId}/': {
      id: '/{$sportId}/'
      path: '/{$sportId}'
      fullPath: '/{$sportId}/'
      preLoaderRoute: typeof Char123sportIdChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{$sportId}/{$seasonId}/': {
      id: '/{$sportId}/{$seasonId}/'
      path: '/{$sportId}/{$seasonId}'
      fullPath: '/{$sportId}/{$seasonId}/'
      preLoaderRoute: typeof Char123sportIdChar125Char123seasonIdChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{$sportId}/{$seasonId}/{$teamId}/': {
      id: '/{$sportId}/{$seasonId}/{$teamId}/'
      path: '/{$sportId}/{$seasonId}/{$teamId}'
      fullPath: '/{$sportId}/{$seasonId}/{$teamId}/'
      preLoaderRoute: typeof Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char123sportIdChar125IndexRoute: Char123sportIdChar125IndexRoute,
  Char123sportIdChar125Char123seasonIdChar125IndexRoute:
    Char123sportIdChar125Char123seasonIdChar125IndexRoute,
  Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRoute:
    Char123sportIdChar125Char123seasonIdChar125Char123teamIdChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
