/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeasonYearRouteImport } from './routes/season.$year'
import { Route as SeasonYearIndexRouteImport } from './routes/season.$year.index'
import { Route as SeasonYearGamesGamePkRouteImport } from './routes/season.$year.games.$gamePk'
import { Route as SeasonYearTeamsTeamIdRouteImport } from './routes/season.$year.teams.$teamId'
import { Route as SeasonYearTeamsTeamIdRosterRouteImport } from './routes/season.$year.teams.$teamId.roster'
import { Route as SeasonYearGamesGamePkPlayersPersonIdRouteImport } from './routes/season.$year.games.$gamePk.players.$personId'
import { Route as SeasonYearTeamsTeamIdGamesGamePkRouteImport } from './routes/season.$year.teams.$teamId.games.$gamePk'
import { Route as SeasonYearTeamsTeamIdRosterPlayersPersonIdRouteImport } from './routes/season.$year.teams.$teamId.roster.players.$personId'
import { Route as SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRouteImport } from './routes/season.$year.teams.$teamId.games.$gamePk.players.$personId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonYearRoute = SeasonYearRouteImport.update({
  id: '/season/$year',
  path: '/season/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonYearIndexRoute = SeasonYearIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeasonYearRoute,
} as any)
const SeasonYearGamesGamePkRoute = SeasonYearGamesGamePkRouteImport.update({
  id: '/games/$gamePk',
  path: '/games/$gamePk',
  getParentRoute: () => SeasonYearRoute,
} as any)
const SeasonYearTeamsTeamIdRoute = SeasonYearTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => SeasonYearRoute,
} as any)
const SeasonYearTeamsTeamIdRosterRoute =
  SeasonYearTeamsTeamIdRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => SeasonYearTeamsTeamIdRoute,
  } as any)
const SeasonYearGamesGamePkPlayersPersonIdRoute =
  SeasonYearGamesGamePkPlayersPersonIdRouteImport.update({
    id: '/players/$personId',
    path: '/players/$personId',
    getParentRoute: () => SeasonYearGamesGamePkRoute,
  } as any)
const SeasonYearTeamsTeamIdGamesGamePkRoute =
  SeasonYearTeamsTeamIdGamesGamePkRouteImport.update({
    id: '/games/$gamePk',
    path: '/games/$gamePk',
    getParentRoute: () => SeasonYearTeamsTeamIdRoute,
  } as any)
const SeasonYearTeamsTeamIdRosterPlayersPersonIdRoute =
  SeasonYearTeamsTeamIdRosterPlayersPersonIdRouteImport.update({
    id: '/players/$personId',
    path: '/players/$personId',
    getParentRoute: () => SeasonYearTeamsTeamIdRosterRoute,
  } as any)
const SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRoute =
  SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRouteImport.update({
    id: '/players/$personId',
    path: '/players/$personId',
    getParentRoute: () => SeasonYearTeamsTeamIdGamesGamePkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/season/$year': typeof SeasonYearRouteWithChildren
  '/season/$year/': typeof SeasonYearIndexRoute
  '/season/$year/games/$gamePk': typeof SeasonYearGamesGamePkRouteWithChildren
  '/season/$year/teams/$teamId': typeof SeasonYearTeamsTeamIdRouteWithChildren
  '/season/$year/teams/$teamId/roster': typeof SeasonYearTeamsTeamIdRosterRouteWithChildren
  '/season/$year/games/$gamePk/players/$personId': typeof SeasonYearGamesGamePkPlayersPersonIdRoute
  '/season/$year/teams/$teamId/games/$gamePk': typeof SeasonYearTeamsTeamIdGamesGamePkRouteWithChildren
  '/season/$year/teams/$teamId/roster/players/$personId': typeof SeasonYearTeamsTeamIdRosterPlayersPersonIdRoute
  '/season/$year/teams/$teamId/games/$gamePk/players/$personId': typeof SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/season/$year': typeof SeasonYearIndexRoute
  '/season/$year/games/$gamePk': typeof SeasonYearGamesGamePkRouteWithChildren
  '/season/$year/teams/$teamId': typeof SeasonYearTeamsTeamIdRouteWithChildren
  '/season/$year/teams/$teamId/roster': typeof SeasonYearTeamsTeamIdRosterRouteWithChildren
  '/season/$year/games/$gamePk/players/$personId': typeof SeasonYearGamesGamePkPlayersPersonIdRoute
  '/season/$year/teams/$teamId/games/$gamePk': typeof SeasonYearTeamsTeamIdGamesGamePkRouteWithChildren
  '/season/$year/teams/$teamId/roster/players/$personId': typeof SeasonYearTeamsTeamIdRosterPlayersPersonIdRoute
  '/season/$year/teams/$teamId/games/$gamePk/players/$personId': typeof SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/season/$year': typeof SeasonYearRouteWithChildren
  '/season/$year/': typeof SeasonYearIndexRoute
  '/season/$year/games/$gamePk': typeof SeasonYearGamesGamePkRouteWithChildren
  '/season/$year/teams/$teamId': typeof SeasonYearTeamsTeamIdRouteWithChildren
  '/season/$year/teams/$teamId/roster': typeof SeasonYearTeamsTeamIdRosterRouteWithChildren
  '/season/$year/games/$gamePk/players/$personId': typeof SeasonYearGamesGamePkPlayersPersonIdRoute
  '/season/$year/teams/$teamId/games/$gamePk': typeof SeasonYearTeamsTeamIdGamesGamePkRouteWithChildren
  '/season/$year/teams/$teamId/roster/players/$personId': typeof SeasonYearTeamsTeamIdRosterPlayersPersonIdRoute
  '/season/$year/teams/$teamId/games/$gamePk/players/$personId': typeof SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/season/$year'
    | '/season/$year/'
    | '/season/$year/games/$gamePk'
    | '/season/$year/teams/$teamId'
    | '/season/$year/teams/$teamId/roster'
    | '/season/$year/games/$gamePk/players/$personId'
    | '/season/$year/teams/$teamId/games/$gamePk'
    | '/season/$year/teams/$teamId/roster/players/$personId'
    | '/season/$year/teams/$teamId/games/$gamePk/players/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/season/$year'
    | '/season/$year/games/$gamePk'
    | '/season/$year/teams/$teamId'
    | '/season/$year/teams/$teamId/roster'
    | '/season/$year/games/$gamePk/players/$personId'
    | '/season/$year/teams/$teamId/games/$gamePk'
    | '/season/$year/teams/$teamId/roster/players/$personId'
    | '/season/$year/teams/$teamId/games/$gamePk/players/$personId'
  id:
    | '__root__'
    | '/'
    | '/season/$year'
    | '/season/$year/'
    | '/season/$year/games/$gamePk'
    | '/season/$year/teams/$teamId'
    | '/season/$year/teams/$teamId/roster'
    | '/season/$year/games/$gamePk/players/$personId'
    | '/season/$year/teams/$teamId/games/$gamePk'
    | '/season/$year/teams/$teamId/roster/players/$personId'
    | '/season/$year/teams/$teamId/games/$gamePk/players/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeasonYearRoute: typeof SeasonYearRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season/$year': {
      id: '/season/$year'
      path: '/season/$year'
      fullPath: '/season/$year'
      preLoaderRoute: typeof SeasonYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season/$year/': {
      id: '/season/$year/'
      path: '/'
      fullPath: '/season/$year/'
      preLoaderRoute: typeof SeasonYearIndexRouteImport
      parentRoute: typeof SeasonYearRoute
    }
    '/season/$year/games/$gamePk': {
      id: '/season/$year/games/$gamePk'
      path: '/games/$gamePk'
      fullPath: '/season/$year/games/$gamePk'
      preLoaderRoute: typeof SeasonYearGamesGamePkRouteImport
      parentRoute: typeof SeasonYearRoute
    }
    '/season/$year/teams/$teamId': {
      id: '/season/$year/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/season/$year/teams/$teamId'
      preLoaderRoute: typeof SeasonYearTeamsTeamIdRouteImport
      parentRoute: typeof SeasonYearRoute
    }
    '/season/$year/teams/$teamId/roster': {
      id: '/season/$year/teams/$teamId/roster'
      path: '/roster'
      fullPath: '/season/$year/teams/$teamId/roster'
      preLoaderRoute: typeof SeasonYearTeamsTeamIdRosterRouteImport
      parentRoute: typeof SeasonYearTeamsTeamIdRoute
    }
    '/season/$year/games/$gamePk/players/$personId': {
      id: '/season/$year/games/$gamePk/players/$personId'
      path: '/players/$personId'
      fullPath: '/season/$year/games/$gamePk/players/$personId'
      preLoaderRoute: typeof SeasonYearGamesGamePkPlayersPersonIdRouteImport
      parentRoute: typeof SeasonYearGamesGamePkRoute
    }
    '/season/$year/teams/$teamId/games/$gamePk': {
      id: '/season/$year/teams/$teamId/games/$gamePk'
      path: '/games/$gamePk'
      fullPath: '/season/$year/teams/$teamId/games/$gamePk'
      preLoaderRoute: typeof SeasonYearTeamsTeamIdGamesGamePkRouteImport
      parentRoute: typeof SeasonYearTeamsTeamIdRoute
    }
    '/season/$year/teams/$teamId/roster/players/$personId': {
      id: '/season/$year/teams/$teamId/roster/players/$personId'
      path: '/players/$personId'
      fullPath: '/season/$year/teams/$teamId/roster/players/$personId'
      preLoaderRoute: typeof SeasonYearTeamsTeamIdRosterPlayersPersonIdRouteImport
      parentRoute: typeof SeasonYearTeamsTeamIdRosterRoute
    }
    '/season/$year/teams/$teamId/games/$gamePk/players/$personId': {
      id: '/season/$year/teams/$teamId/games/$gamePk/players/$personId'
      path: '/players/$personId'
      fullPath: '/season/$year/teams/$teamId/games/$gamePk/players/$personId'
      preLoaderRoute: typeof SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRouteImport
      parentRoute: typeof SeasonYearTeamsTeamIdGamesGamePkRoute
    }
  }
}

interface SeasonYearGamesGamePkRouteChildren {
  SeasonYearGamesGamePkPlayersPersonIdRoute: typeof SeasonYearGamesGamePkPlayersPersonIdRoute
}

const SeasonYearGamesGamePkRouteChildren: SeasonYearGamesGamePkRouteChildren = {
  SeasonYearGamesGamePkPlayersPersonIdRoute:
    SeasonYearGamesGamePkPlayersPersonIdRoute,
}

const SeasonYearGamesGamePkRouteWithChildren =
  SeasonYearGamesGamePkRoute._addFileChildren(
    SeasonYearGamesGamePkRouteChildren,
  )

interface SeasonYearTeamsTeamIdRosterRouteChildren {
  SeasonYearTeamsTeamIdRosterPlayersPersonIdRoute: typeof SeasonYearTeamsTeamIdRosterPlayersPersonIdRoute
}

const SeasonYearTeamsTeamIdRosterRouteChildren: SeasonYearTeamsTeamIdRosterRouteChildren =
  {
    SeasonYearTeamsTeamIdRosterPlayersPersonIdRoute:
      SeasonYearTeamsTeamIdRosterPlayersPersonIdRoute,
  }

const SeasonYearTeamsTeamIdRosterRouteWithChildren =
  SeasonYearTeamsTeamIdRosterRoute._addFileChildren(
    SeasonYearTeamsTeamIdRosterRouteChildren,
  )

interface SeasonYearTeamsTeamIdGamesGamePkRouteChildren {
  SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRoute: typeof SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRoute
}

const SeasonYearTeamsTeamIdGamesGamePkRouteChildren: SeasonYearTeamsTeamIdGamesGamePkRouteChildren =
  {
    SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRoute:
      SeasonYearTeamsTeamIdGamesGamePkPlayersPersonIdRoute,
  }

const SeasonYearTeamsTeamIdGamesGamePkRouteWithChildren =
  SeasonYearTeamsTeamIdGamesGamePkRoute._addFileChildren(
    SeasonYearTeamsTeamIdGamesGamePkRouteChildren,
  )

interface SeasonYearTeamsTeamIdRouteChildren {
  SeasonYearTeamsTeamIdRosterRoute: typeof SeasonYearTeamsTeamIdRosterRouteWithChildren
  SeasonYearTeamsTeamIdGamesGamePkRoute: typeof SeasonYearTeamsTeamIdGamesGamePkRouteWithChildren
}

const SeasonYearTeamsTeamIdRouteChildren: SeasonYearTeamsTeamIdRouteChildren = {
  SeasonYearTeamsTeamIdRosterRoute:
    SeasonYearTeamsTeamIdRosterRouteWithChildren,
  SeasonYearTeamsTeamIdGamesGamePkRoute:
    SeasonYearTeamsTeamIdGamesGamePkRouteWithChildren,
}

const SeasonYearTeamsTeamIdRouteWithChildren =
  SeasonYearTeamsTeamIdRoute._addFileChildren(
    SeasonYearTeamsTeamIdRouteChildren,
  )

interface SeasonYearRouteChildren {
  SeasonYearIndexRoute: typeof SeasonYearIndexRoute
  SeasonYearGamesGamePkRoute: typeof SeasonYearGamesGamePkRouteWithChildren
  SeasonYearTeamsTeamIdRoute: typeof SeasonYearTeamsTeamIdRouteWithChildren
}

const SeasonYearRouteChildren: SeasonYearRouteChildren = {
  SeasonYearIndexRoute: SeasonYearIndexRoute,
  SeasonYearGamesGamePkRoute: SeasonYearGamesGamePkRouteWithChildren,
  SeasonYearTeamsTeamIdRoute: SeasonYearTeamsTeamIdRouteWithChildren,
}

const SeasonYearRouteWithChildren = SeasonYearRoute._addFileChildren(
  SeasonYearRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeasonYearRoute: SeasonYearRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
